In [89]:
# IMPORTS
import pandas as pd
import json as js

In [90]:
# Lectura de ficheros
rutaC = "C:\\Users\\CarmenGonzalezConde\\Documents\\MASTER\\"
rutaA = ""
rutaO = ""

ruta = rutaC + "PRACTICA_PYTHON-master\\PRACTICA_PYTHON-master\\BaseDeDatos\\"
file = ruta + "tmdb_5000_credits.csv"
file2 = ruta + "tmdb_5000_movies.csv"

credits = pd.read_csv(file, encoding="cp437", delimiter = ',')
movies = pd.read_csv(file2, encoding="cp437", delimiter = ',')

In [91]:
# Merge de Dataframes 

# Cambiamos el nombre a la columa del dataframe movies para poder hacer el merge.
movies = movies.rename(columns= {'id': 'movie_id'})

# Hacemos el merge
dfMerge = pd.merge(credits, movies, on='movie_id')

# Para un mayor rendimiento
dfMerge = dfMerge.head()

# Montamos nuestro dataframe principal
dfPrincipal = dfMerge[['movie_id','original_title', 'original_language', 'popularity', 
                       'release_date', 'revenue', 'runtime', 'status','vote_average', 
                       'vote_count']]

In [92]:
# Montamos los dataframes para las listas

df = dfMerge[['movie_id', 'cast', 'crew', 'genres', 'keywords', 'production_countries',
             'spoken_languages']]

print("Longitud df: ", len(df))

# Inicializamos los dataframes vacíos
dfCast = []
dfCrew = []
dfGenres = []
dfKW = []
dfPCountries = []
dfSLanguages = []

# Nota: Por cada append, se vacía la variable que contiene el json para ahorrar memoria.
for i in range(len(df)):
    id = df['movie_id'][i]
    print("contador: ", i, " Id -> ", id )
    
    # Montamos el dataframe de casts
    castJson = pd.read_json(df['cast'][i])
    castJson['movie_id'] = id
    dfCast.append(castJson[['movie_id', 'name', 'character', 'gender']])
    castJson = [] 
    
    # Montamos el dataframe de crew
    crewJson = pd.read_json(df['crew'][i])
    crewJson['movie_id'] = id
    dfCrew.append(crewJson[['movie_id', 'name', 'gender', 'department', 'job']])
    crewJson = []
    
    # Montamos el dataframe de genres
    genresJson = pd.read_json(df['genres'][i])
    genresJson['movie_id'] = id
    dfGenres.append(genresJson[['movie_id', 'name']])
    genresJson = []
    
    # Montamos el dataframe de Keywords
    kwJson = pd.read_json(df['keywords'][i])
    kwJson['movie_id'] = id
    dfKW.append(kwJson[['movie_id', 'name']])
    kwJson = []
    
    # Montamos el dataframe de production_countries
    pcJson = pd.read_json(df['production_countries'][i])
    pcJson['movie_id'] = id
    dfPCountries.append(pcJson[['movie_id', 'name']])
    pcJson = []
    
    # Montamos el dataframe de spoken_languages
    slJson = pd.read_json(df['spoken_languages'][i])
    slJson['movie_id'] = id
    dfSLanguages.append(slJson[['movie_id', 'name']])
    slJson = []
    
    
# Concatenamos para que devuelva dataframe
dfCast = pd.concat(dfCast)
dfCrew = pd.concat(dfCrew)
dfGenres = pd.concat(dfGenres)
dfKW = pd.concat(dfKW)
dfPCountries = pd.concat(dfPCountries)
dfSLanguages = pd.concat(dfSLanguages)

print(dfCast.head())

# Vaciamos el dataframe dfMerge para un mejor rendimiento, no lo volveremos a usar.
dfMerge = []

Longitud df:  5
contador:  0  Id ->  19995
contador:  1  Id ->  285
contador:  2  Id ->  206647
contador:  3  Id ->  49026
contador:  4  Id ->  49529
   movie_id                name            character  gender
0     19995     Sam Worthington           Jake Sully       2
1     19995         Zoe Saldana              Neytiri       1
2     19995    Sigourney Weaver  Dr. Grace Augustine       1
3     19995        Stephen Lang        Col. Quaritch       2
4     19995  Michelle Rodriguez         Trudy Chacon       1

In [93]:
# Ejemplo: Mostramos el dataframe keywords.

print(dfKW)

    movie_id                        name
0      19995               culture clash
1      19995                      future
2      19995                   space war
3      19995                space colony
4      19995                     society
5      19995                space travel
6      19995                  futuristic
7      19995                     romance
8      19995                       space
9      19995                       alien
10     19995                       tribe
11     19995                alien planet
12     19995                         cgi
13     19995                      marine
14     19995                     soldier
15     19995                      battle
16     19995                 love affair
17     19995                    anti war
18     19995             power relations
19     19995               mind and soul
20     19995                          3d
0        285                       ocean
1        285                  drug abuse
2        285               exotic island
3        285  east india trading company
4        285          love of one's life
5        285                     traitor
6        285                   shipwreck
7        285                strong woman
8        285                        ship
..       ...                         ...
7      49026                 gotham city
8      49026                   vigilante
9      49026                    cover-up
10     49026                   superhero
11     49026                  villainess
12     49026                 tragic hero
13     49026                   terrorism
14     49026                 destruction
15     49026                    catwoman
16     49026                 cat burglar
17     49026                        imax
18     49026                       flood
19     49026         criminal underworld
20     49026                      batman
0      49529              based on novel
1      49529                        mars
2      49529                   medallion
3      49529                space travel
4      49529                    princess
5      49529                       alien
6      49529                   steampunk
7      49529                     martian
8      49529                      escape
9      49529        edgar rice burroughs
10     49529                  alien race
11     49529         superhuman strength
12     49529           mars civilization
13     49529            sword and planet
14     49529                19th century
15     49529                          3d

[81 rows x 2 columns]